version: '3.9'

services: 
      
  db:
    container_name: peniel-db
    image: postgres:14-alpine
    restart: always
    env_file:
      - .docker.env
    networks: 
      - peniel
    volumes:
      - .\initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - .\db\postgres\data:/var/lib/postgresql/data
    ports:
      - 5432:5432     
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5 

  api:
    container_name: peniel-api
    build: 
      context: .
      dockerfile: ./Dockerfile
    entrypoint: ./api.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks: 
      - peniel      
    depends_on: 
      - db   

networks: 
  peniel:
    driver: bridge
